package li.masciul.sugardaddi.utils.image;

import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Context;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.provider.MediaStore;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * ImageStorageManager — Disk-only image storage for SugarDaddi.
 *
 * RESPONSIBILITIES
 * ================
 * - Define and create the on-disk directory structure under getExternalFilesDir()
 * - Construct deterministic file paths for each image category
 * - Create, check existence of, and delete image files
 * - Opt individual files into the device gallery via MediaScannerConnection
 * - Remove files from the device gallery via ContentResolver
 *
 * WHAT THIS CLASS DOES NOT DO
 * ============================
 * - No network operations   → ThumbnailDownloader
 * - No image processing     → ImageProcessor
 * - No database access      → ImagePurgeManager
 * - No camera/gallery UI    → ImagePickerHelper
 *
 * DIRECTORY STRUCTURE
 * ====================
 *
 *   getExternalFilesDir(null)/
 *   └── sugardaddi/
 *       ├── thumbnails/    ← auto-cached remote thumbnails, all item types
 *       │                    Never gallery-scanned. Managed by ThumbnailDownloader.
 *       ├── products/      ← user-added hero images for food products
 *       ├── recipes/       ← user-added hero images for recipes
 *       ├── meals/         ← photos attached to meal journal entries
 *       └── steps/         ← instructional photos for recipe preparation steps
 *
 * GALLERY VISIBILITY
 * ==================
 * thumbnails/ is always private — never scanned to the gallery.
 * products/, recipes/, meals/, and steps/ are candidates for gallery scanning,
 * controlled by the user via Settings. Scanning is opt-in per file via
 * scanFile() / unscanFile().
 *
 * PERMISSIONS
 * ===========
 * getExternalFilesDir() is app-private on API 29+ — no READ/WRITE_EXTERNAL_STORAGE
 * permissions are required.
 *
 * FILENAME CONVENTIONS
 * ====================
 * Thumbnails  : {sanitised source-qualified ID}.jpg  e.g. "OFF_3017620422003.jpg"
 *               Source-qualified IDs use ':' which is illegal on FAT32/exFAT —
 *               the colon is replaced with '_' by sanitiseId().
 *               Natural deduplication: same item always resolves to the same file.
 * User photos : {UUID}.jpg  — generated by the caller (ImagePickerHelper).
 *               UUIDs are filesystem-safe on all platforms.
 */
public class ImageStorageManager {

    private static final String TAG = "SugarDaddi_Images";

    // =========================================================================
    // DIRECTORY NAME CONSTANTS
    // =========================================================================

    /** Top-level app directory inside getExternalFilesDir(). */
    private static final String DIR_ROOT       = "sugardaddi";

    /** Auto-cached remote thumbnails — all item types, never gallery-scanned. */
    private static final String DIR_THUMBNAILS = "thumbnails";

    /** User-added hero images for food products. */
    private static final String DIR_PRODUCTS   = "products";

    /** User-added hero images for recipes. */
    private static final String DIR_RECIPES    = "recipes";

    /** User photos attached to meal journal entries. */
    private static final String DIR_MEALS      = "meals";

    /** Instructional photos for recipe preparation steps. */
    private static final String DIR_STEPS      = "steps";

    // =========================================================================
    // STATE
    // =========================================================================

    private final Context context;

    // =========================================================================
    // CONSTRUCTOR
    // =========================================================================

    /**
     * @param context Application context. Prefer application context over activity
     *                context — this instance may outlive any individual Activity.
     */
    public ImageStorageManager(@NonNull Context context) {
        this.context = context.getApplicationContext();
    }

    // =========================================================================
    // DIRECTORY ACCESS
    // =========================================================================

    /**
     * Returns (and creates if necessary) the root sugardaddi/ directory.
     *
     * Uses getExternalFilesDir(null) — app-private, no permissions required on
     * API 29+. Returns null and logs if external storage is unavailable.
     *
     * @return The root File, or null if external storage is not available.
     */
    @Nullable
    public File getRootDir() {
        File extBase = context.getExternalFilesDir(null);
        if (extBase == null) {
            Log.e(TAG, "External files dir unavailable — cannot access image storage");
            return null;
        }
        return ensureDir(new File(extBase, DIR_ROOT));
    }

    /**
     * Returns (and creates if necessary) the thumbnails/ directory.
     * Files here are NEVER gallery-scanned.
     */
    @Nullable
    public File getThumbnailsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(root, DIR_THUMBNAILS));
    }

    /**
     * Returns (and creates if necessary) the products/ directory.
     * Gallery-scanning is opt-in per file.
     */
    @Nullable
    public File getProductsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(root, DIR_PRODUCTS));
    }

    /**
     * Returns (and creates if necessary) the recipes/ directory.
     * Gallery-scanning is opt-in per file.
     */
    @Nullable
    public File getRecipesDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(root, DIR_RECIPES));
    }

    /**
     * Returns (and creates if necessary) the meals/ directory.
     * Gallery-scanning is opt-in per file.
     */
    @Nullable
    public File getMealsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(root, DIR_MEALS));
    }

    /**
     * Returns (and creates if necessary) the steps/ directory.
     * Gallery-scanning is opt-in per file.
     */
    @Nullable
    public File getStepsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(root, DIR_STEPS));
    }

    // =========================================================================
    // PATH CONSTRUCTION
    // =========================================================================

    /**
     * Constructs the expected File for a cached thumbnail.
     *
     * Filename is derived from the source-qualified item ID (e.g. "OFF:3017620422003").
     * ':' is replaced with '_' because colon is illegal on FAT32/exFAT.
     * Natural deduplication: re-favouriting the same item always produces the same
     * filename, so no duplicate downloads ever occur.
     *
     * @param sourceQualifiedId The item's source-qualified ID, e.g. "OFF:3017620422003".
     * @return A File pointing to the expected thumbnail location, or null if unavailable.
     */
    @Nullable
    public File getThumbnailFile(@NonNull String sourceQualifiedId) {
        File dir = getThumbnailsDir();
        if (dir == null) return null;
        return new File(dir, sanitiseId(sourceQualifiedId) + ".jpg");
    }

    /**
     * Constructs a File for a food product hero image.
     *
     * @param filename Filesystem-safe filename with extension, e.g. "{UUID}.jpg".
     *                 UUID generation is the caller's responsibility (ImagePickerHelper).
     * @return A File at the expected path, or null if the directory is unavailable.
     */
    @Nullable
    public File getProductHeroFile(@NonNull String filename) {
        File dir = getProductsDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    /**
     * Constructs a File for a recipe hero image.
     *
     * @param filename Filesystem-safe filename with extension, e.g. "{UUID}.jpg".
     * @return A File at the expected path, or null if the directory is unavailable.
     */
    @Nullable
    public File getRecipeHeroFile(@NonNull String filename) {
        File dir = getRecipesDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    /**
     * Constructs a File for a meal journal photo.
     *
     * @param filename Filesystem-safe filename with extension, e.g. "{UUID}.jpg".
     * @return A File at the expected path, or null if the directory is unavailable.
     */
    @Nullable
    public File getMealPhotoFile(@NonNull String filename) {
        File dir = getMealsDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    /**
     * Constructs a File for a recipe step photo.
     *
     * @param filename Filesystem-safe filename with extension, e.g. "{UUID}.jpg".
     * @return A File at the expected path, or null if the directory is unavailable.
     */
    @Nullable
    public File getStepPhotoFile(@NonNull String filename) {
        File dir = getStepsDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    // =========================================================================
    // FILE OPERATIONS
    // =========================================================================

    /**
     * Returns true if the file at the given path exists and is a regular file.
     * Safe to call with a null path — returns false.
     *
     * @param path Absolute path string (typically from a Room entity field).
     */
    public boolean exists(@Nullable String path) {
        if (path == null || path.trim().isEmpty()) return false;
        File f = new File(path);
        return f.exists() && f.isFile();
    }

    /**
     * Deletes the file at the given absolute path.
     *
     * Safe to call with a null path — returns false without logging.
     *
     * NOTE: Does NOT remove the file from MediaStore. If the file was previously
     * gallery-scanned, call unscanFile() BEFORE this method to keep MediaStore
     * consistent and avoid broken thumbnails in gallery apps.
     *
     * @param path Absolute path string (typically from a Room entity field).
     * @return true if the file was deleted; false if it didn't exist or deletion failed.
     */
    public boolean deleteFile(@Nullable String path) {
        if (path == null || path.trim().isEmpty()) return false;

        File f = new File(path);
        if (!f.exists()) return false; // Already gone — desired outcome.

        boolean deleted = f.delete();
        if (!deleted) Log.w(TAG, "Failed to delete image: " + path);
        else          Log.d(TAG, "Deleted image: " + path);
        return deleted;
    }

    /**
     * Creates an empty File at the given location, suitable for writing into.
     *
     * Required by ImagePickerHelper before launching the camera intent — the camera
     * app needs a pre-existing URI to write the photo into. Parent directories are
     * created if missing.
     *
     * @param file The target File (path already set via a getXxxFile() call).
     * @return The same File if creation succeeded, or null on failure.
     */
    @Nullable
    public File createEmptyFile(@NonNull File file) {
        try {
            File parent = file.getParentFile();
            if (parent != null && !parent.exists()) {
                if (!parent.mkdirs()) {
                    Log.e(TAG, "Failed to create parent dirs for: " + file.getAbsolutePath());
                    return null;
                }
            }
            if (file.createNewFile()) {
                Log.d(TAG, "Created empty file: " + file.getAbsolutePath());
                return file;
            } else {
                // File already exists — acceptable after a crash/retry.
                Log.d(TAG, "File already exists (reusing): " + file.getAbsolutePath());
                return file;
            }
        } catch (IOException e) {
            Log.e(TAG, "Failed to create empty file: " + file.getAbsolutePath(), e);
            return null;
        }
    }

    // =========================================================================
    // GALLERY SCANNING (opt-in, for products/, recipes/, meals/, steps/ only)
    // =========================================================================

    /**
     * Makes the given file visible in the device gallery by inserting it into
     * the public MediaStore.Images collection via ContentResolver.
     *
     * WHY NOT MediaScannerConnection.scanFile()
     * ==========================================
     * Files in getExternalFilesDir() are app-private by design and will not be
     * indexed by MediaStore — MediaScannerConnection.scanFile() silently does
     * nothing for these paths. The correct API 29+ approach is to insert the
     * file content directly into MediaStore via ContentResolver.insert() +
     * openOutputStream(), which creates a gallery-visible copy.
     *
     * HOW IT WORKS
     * =============
     * A new MediaStore.Images entry is created and the file bytes are written
     * into it. The original file in app-private storage is NOT deleted — it
     * remains the authoritative copy referenced by Room. The MediaStore entry
     * is what makes the image visible in gallery apps.
     *
     * REMOVAL
     * ========
     * To remove from the gallery, call unscanFile(). This queries MediaStore
     * by display name and deletes the entry. If the user has already deleted
     * the image manually from their gallery, unscanFile() returns false
     * gracefully — the entry is already gone.
     *
     * NEVER call this for files in thumbnails/ — those are always private.
     *
     * @param file     The app-private file to make visible in the gallery.
     * @param callback Optional; called with (path, uri) on success or
     *                 (path, null) on failure. Called on the calling thread —
     *                 if you need main thread delivery, post it yourself.
     */
    public void scanFile(
            @NonNull File file,
            @Nullable MediaScannerConnection.OnScanCompletedListener callback) {

        if (!file.exists() || !file.isFile()) {
            Log.w(TAG, "scanFile: file does not exist: " + file.getName());
            if (callback != null) {
                callback.onScanCompleted(file.getAbsolutePath(), null);
            }
            return;
        }

        ContentResolver resolver = context.getContentResolver();

        // Build the MediaStore metadata for the new entry.
        ContentValues values = new ContentValues();
        values.put(MediaStore.Images.Media.DISPLAY_NAME, file.getName());
        values.put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg");
        values.put(MediaStore.Images.Media.DATE_ADDED,
                System.currentTimeMillis() / 1000);
        values.put(MediaStore.Images.Media.IS_PENDING, 1);

        // RELATIVE_PATH places the image in a named album within Pictures/.
        // Gallery apps (Google Photos, Samsung Gallery, etc.) use this path
        // to organise images into albums named "SugarDaddi/{Subfolder}".
        // Ignored on API 26-28 (pre-scoped storage) — images fall back to
        // the default Pictures/ root on those devices.
        values.put(MediaStore.Images.Media.RELATIVE_PATH, getGallerySubfolder(file));

        Uri collection = MediaStore.Images.Media.getContentUri(
                MediaStore.VOLUME_EXTERNAL_PRIMARY);
        Uri itemUri = resolver.insert(collection, values);

        if (itemUri == null) {
            Log.w(TAG, "scanFile: MediaStore insert returned null for: "
                    + file.getName());
            if (callback != null) {
                callback.onScanCompleted(file.getAbsolutePath(), null);
            }
            return;
        }

        // Write the file bytes into the MediaStore entry.
        try (InputStream in  = new FileInputStream(file);
             OutputStream out = resolver.openOutputStream(itemUri)) {

            if (out == null) {
                throw new java.io.IOException("openOutputStream returned null");
            }

            byte[] buffer = new byte[8192];
            int read;
            while ((read = in.read(buffer)) != -1) {
                out.write(buffer, 0, read);
            }
            out.flush();

            // Mark as no longer pending — gallery apps can now show it.
            values.clear();
            values.put(MediaStore.Images.Media.IS_PENDING, 0);
            resolver.update(itemUri, values, null, null);

            Log.d(TAG, "scanFile: added to gallery: " + file.getName());
            if (callback != null) {
                callback.onScanCompleted(file.getAbsolutePath(), itemUri);
            }

        } catch (Exception e) {
            Log.w(TAG, "scanFile: failed to write to MediaStore: "
                    + file.getName(), e);
            // Clean up the orphan MediaStore row.
            resolver.delete(itemUri, null, null);
            if (callback != null) {
                callback.onScanCompleted(file.getAbsolutePath(), null);
            }
        }
    }

    /**
     * Removes the gallery entry for the given file from MediaStore.
     *
     * Queries by DISPLAY_NAME (filename) rather than the DATA path because
     * the MediaStore entry was created via ContentResolver.insert() — its
     * internal path differs from our app-private file path.
     *
     * GRACEFUL HANDLING OF PRIOR MANUAL DELETION
     * ============================================
     * If the user has already deleted the image from their gallery manually,
     * the MediaStore entry is already gone. This method returns false in that
     * case — no crash, no dangling entry, no action needed.
     *
     * This method does NOT delete the original app-private file — it only
     * removes the gallery-visible MediaStore copy. To delete the app-private
     * file, call deleteFile() separately.
     *
     * @param file The file whose gallery entry should be removed.
     * @return true if a MediaStore entry was found and removed;
     *         false if already absent (either never scanned or manually deleted).
     */
    public boolean unscanFile(@NonNull File file) {
        ContentResolver resolver = context.getContentResolver();
        Uri mediaUri = MediaStore.Images.Media.getContentUri(
                MediaStore.VOLUME_EXTERNAL_PRIMARY);

        // Query by display name — this matches the DISPLAY_NAME we set in scanFile().
        // Using DATA path would not match because the MediaStore entry's DATA path
        // points to its own internal copy, not our app-private file.
        String selection = MediaStore.Images.Media.DISPLAY_NAME + " = ?";
        String[] args    = { file.getName() };

        try {
            int removed = resolver.delete(mediaUri, selection, args);
            if (removed > 0) {
                Log.d(TAG, "unscanFile: removed from gallery: " + file.getName());
                return true;
            } else {
                // Not in MediaStore — either never scanned, already removed
                // manually by the user, or previously removed by unscanFile().
                // All three cases are fine — the desired state (not in gallery)
                // is already achieved.
                Log.d(TAG, "unscanFile: not in gallery (no-op): " + file.getName());
                return false;
            }
        } catch (Exception e) {
            // Non-fatal — log and continue.
            Log.w(TAG, "unscanFile: failed for: " + file.getName(), e);
            return false;
        }
    }

    // =========================================================================
    // INTERNAL HELPERS
    // =========================================================================

    /**
     * Ensures the given directory exists, creating it and any missing parents.
     *
     * @return The directory if it exists or was just created, null if mkdirs() failed.
     */
    @Nullable
    private File ensureDir(@NonNull File dir) {
        if (dir.exists() && dir.isDirectory()) return dir;
        if (dir.mkdirs()) {
            Log.d(TAG, "Created directory: " + dir.getAbsolutePath());
            return dir;
        }
        Log.e(TAG, "Failed to create directory: " + dir.getAbsolutePath());
        return null;
    }

    /**
     * Replaces characters illegal on FAT32/exFAT filesystems.
     *
     * Source-qualified IDs use ':' as separator (e.g. "OFF:3017620422003").
     * Colons are invalid on FAT32/exFAT — replaced with '_' to produce a
     * flat, safe, human-readable filename ("OFF_3017620422003.jpg").
     */
    @NonNull
    private String sanitiseId(@NonNull String id) {
        return id.replace(':', '_');
    }

    /**
     * Maps an app-private directory to its gallery subfolder path.
     *
     * Derives the gallery album name from the file's parent directory name,
     * which matches our directory constants (thumbnails, products, recipes,
     * meals, steps). The result is capitalised for clean display in gallery apps.
     *
     * Gallery path format: "Pictures/SugarDaddi/{Subfolder}"
     * Examples:
     *   .../thumbnails/THEMEALDB_52776.jpg  → "Pictures/SugarDaddi/Thumbnails"
     *   .../meals/550e8400.jpg              → "Pictures/SugarDaddi/Meals"
     *   .../steps/7f3b4c1a.jpg             → "Pictures/SugarDaddi/Steps"
     *
     * Falls back to "Pictures/SugarDaddi/" for any unrecognised directory,
     * so images always land somewhere sensible even if the structure changes.
     *
     * RELATIVE_PATH is available from API 29+. On API 26-28 (which predates
     * scoped storage), RELATIVE_PATH is ignored by the system — images are
     * placed in the default Pictures/ root. This is acceptable since API 26-28
     * represents a negligible fraction of active Android devices.
     *
     * @param file The file being inserted into MediaStore.
     * @return A RELATIVE_PATH string suitable for MediaStore.Images.Media.RELATIVE_PATH.
     */
    @NonNull
    private String getGallerySubfolder(@NonNull File file) {
        File parent = file.getParentFile();
        if (parent == null) return "Pictures/SugarDaddi/";

        // Capitalise the first letter of the directory name for clean display.
        // e.g. "thumbnails" → "Thumbnails", "meals" → "Meals"
        String dirName = parent.getName();
        if (dirName.isEmpty()) return "Pictures/SugarDaddi/";

        String capitalised = dirName.substring(0, 1).toUpperCase()
                + dirName.substring(1);

        return "Pictures/SugarDaddi/" + capitalised + "/";
    }
}