package li.masciul.sugardaddi.utils.image;

import android.content.ContentResolver;
import android.content.Context;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.provider.MediaStore;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.io.File;
import java.io.IOException;

/**
 * ImageStorageManager — Disk-only image storage for SugarDaddi.
 *
 * RESPONSIBILITIES
 * ================
 * - Define and create the on-disk directory structure under getExternalFilesDir()
 * - Construct deterministic file paths for each image category
 * - Create, check existence of, and delete image files
 * - Opt individual files into the device gallery via MediaScannerConnection (meals, steps)
 * - Remove files from the device gallery via ContentResolver (meals, steps)
 *
 * WHAT THIS CLASS DOES NOT DO
 * ============================
 * - No network operations   → see ThumbnailDownloader
 * - No image processing     → see ImageProcessor
 * - No database access      → see ImagePurgeManager
 * - No camera/gallery UI    → see ImagePickerHelper
 *
 * DIRECTORY STRUCTURE
 * ====================
 *
 *   getExternalFilesDir(null)/
 *   └── sugardaddi/
 *       ├── cache/
 *       │   └── thumbnails/   ← auto-downloaded or user-replaced thumbnails
 *       │                       (favourites, all item types, NEVER gallery-scanned)
 *       └── photos/
 *           ├── products/     ← user-added hero images for food products
 *           ├── meals/        ← user photos attached to meal journal entries
 *           └── steps/        ← user photos attached to recipe preparation steps
 *
 * GALLERY VISIBILITY
 * ==================
 * Only photos/ subdirectories are candidates for gallery scanning.
 * cache/thumbnails/ is always private.
 * Scanning is opt-in per file via scanFile() / unscanFile().
 *
 * PERMISSIONS
 * ===========
 * getExternalFilesDir() is app-private on API 29+ — no READ_EXTERNAL_STORAGE
 * or WRITE_EXTERNAL_STORAGE permissions are needed.
 *
 * FILENAME CONVENTIONS
 * ====================
 * Thumbnails  : {sanitised source-qualified ID}.jpg  e.g. "OFF_3017620422003.jpg"
 *               Source-qualified IDs use ':' which is invalid on FAT32/exFAT —
 *               the colon is replaced with '_' by sanitiseId().
 * User photos : {UUID}.jpg  — generated by the caller (ImagePickerHelper)
 *               UUIDs are filesystem-safe on all platforms.
 */
public class ImageStorageManager {

    private static final String TAG = "SugarDaddi_Images";

    // =========================================================================
    // DIRECTORY NAME CONSTANTS
    // =========================================================================

    /** Top-level app directory inside getExternalFilesDir(). */
    private static final String DIR_ROOT        = "sugardaddi";

    /** Subdirectory for auto-managed cached images (thumbnails). */
    private static final String DIR_CACHE        = "cache";

    /** Subdirectory for auto-downloaded / user-replaced thumbnails. */
    private static final String DIR_THUMBNAILS   = "thumbnails";

    /** Subdirectory for user-created photos. */
    private static final String DIR_PHOTOS       = "photos";

    /** Subdirectory for food product hero images. */
    private static final String DIR_PRODUCTS     = "products";

    /** Subdirectory for meal journal photos. */
    private static final String DIR_MEALS        = "meals";

    /** Subdirectory for recipe step photos. */
    private static final String DIR_STEPS        = "steps";

    // =========================================================================
    // STATE
    // =========================================================================

    private final Context context;

    // =========================================================================
    // CONSTRUCTOR
    // =========================================================================

    /**
     * @param context Application context. The instance must outlive any file operations
     *                performed through it, so prefer application context over activity context.
     */
    public ImageStorageManager(@NonNull Context context) {
        this.context = context.getApplicationContext();
    }

    // =========================================================================
    // DIRECTORY ACCESS
    // =========================================================================

    /**
     * Returns (and creates if necessary) the root sugardaddi/ directory.
     *
     * Uses getExternalFilesDir(null) as the parent — app-private, no permissions
     * required on API 29+. Returns null and logs if external storage is unavailable
     * (e.g. SD card removed), so callers must null-check.
     *
     * @return The root File, or null if external storage is not available.
     */
    @Nullable
    public File getRootDir() {
        File extBase = context.getExternalFilesDir(null);
        if (extBase == null) {
            Log.e(TAG, "External files dir is unavailable — cannot access image storage");
            return null;
        }
        return ensureDir(new File(extBase, DIR_ROOT));
    }

    /**
     * Returns (and creates if necessary) the cache/thumbnails/ directory.
     * Files here are NEVER gallery-scanned.
     *
     * @return The thumbnails directory, or null if the root is unavailable.
     */
    @Nullable
    public File getThumbnailsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(new File(root, DIR_CACHE), DIR_THUMBNAILS));
    }

    /**
     * Returns (and creates if necessary) the photos/products/ directory.
     * Gallery-scanning is opt-in — call scanFile() after saving if desired.
     *
     * @return The products photo directory, or null if the root is unavailable.
     */
    @Nullable
    public File getProductPhotosDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(new File(root, DIR_PHOTOS), DIR_PRODUCTS));
    }

    /**
     * Returns (and creates if necessary) the photos/meals/ directory.
     * Gallery-scanning is opt-in — call scanFile() after saving if desired.
     *
     * @return The meals photo directory, or null if the root is unavailable.
     */
    @Nullable
    public File getMealsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(new File(root, DIR_PHOTOS), DIR_MEALS));
    }

    /**
     * Returns (and creates if necessary) the photos/steps/ directory.
     * Gallery-scanning is opt-in — call scanFile() after saving if desired.
     *
     * @return The steps photo directory, or null if the root is unavailable.
     */
    @Nullable
    public File getStepsDir() {
        File root = getRootDir();
        if (root == null) return null;
        return ensureDir(new File(new File(root, DIR_PHOTOS), DIR_STEPS));
    }

    // =========================================================================
    // PATH CONSTRUCTION
    // =========================================================================

    /**
     * Constructs the expected File path for a favourite thumbnail.
     *
     * The filename is derived from the source-qualified item ID (e.g. "OFF:3017620422003").
     * The colon separator is replaced with '_' because ':' is illegal on FAT32/exFAT
     * filesystems (common on external storage). This gives natural deduplication:
     * re-favouriting the same item always produces the same filename.
     *
     * @param sourceQualifiedId The item's source-qualified ID, e.g. "OFF:3017620422003".
     * @return A File object pointing to the expected thumbnail location,
     *         or null if the directory is unavailable.
     */
    @Nullable
    public File getThumbnailFile(@NonNull String sourceQualifiedId) {
        File dir = getThumbnailsDir();
        if (dir == null) return null;
        return new File(dir, sanitiseId(sourceQualifiedId) + ".jpg");
    }

    /**
     * Constructs the expected File path for a food product hero image.
     *
     * @param filename A filesystem-safe filename with extension, e.g. "550e8400-e29b-41d4-a716.jpg".
     *                 The caller (ImagePickerHelper) is responsible for generating a UUID-based name.
     * @return A File object pointing to the expected location,
     *         or null if the directory is unavailable.
     */
    @Nullable
    public File getProductPhotoFile(@NonNull String filename) {
        File dir = getProductPhotosDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    /**
     * Constructs the expected File path for a meal journal photo.
     *
     * @param filename A filesystem-safe filename with extension, e.g. "550e8400-e29b-41d4-a716.jpg".
     * @return A File object pointing to the expected location,
     *         or null if the directory is unavailable.
     */
    @Nullable
    public File getMealPhotoFile(@NonNull String filename) {
        File dir = getMealsDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    /**
     * Constructs the expected File path for a recipe step photo.
     *
     * @param filename A filesystem-safe filename with extension, e.g. "550e8400-e29b-41d4-a716.jpg".
     * @return A File object pointing to the expected location,
     *         or null if the directory is unavailable.
     */
    @Nullable
    public File getStepPhotoFile(@NonNull String filename) {
        File dir = getStepsDir();
        if (dir == null) return null;
        return new File(dir, filename);
    }

    // =========================================================================
    // FILE OPERATIONS
    // =========================================================================

    /**
     * Returns true if the file at the given path exists and is a regular file.
     * Safe to call with a null path — returns false.
     *
     * @param path Absolute path string (typically from a Room entity field).
     * @return true if the file exists on disk.
     */
    public boolean exists(@Nullable String path) {
        if (path == null || path.trim().isEmpty()) return false;
        File f = new File(path);
        return f.exists() && f.isFile();
    }

    /**
     * Deletes the file at the given absolute path.
     *
     * Safe to call with a null path — returns false without logging.
     * Logs a warning if the file exists but deletion fails (permissions issue,
     * file locked, etc.).
     *
     * NOTE: This method does NOT remove the file from the MediaStore gallery.
     * If the file was previously scanned into the gallery, call unscanFile()
     * BEFORE calling this method so MediaStore stays consistent.
     *
     * @param path Absolute path string (typically from a Room entity field).
     * @return true if the file was deleted, false if it didn't exist or deletion failed.
     */
    public boolean deleteFile(@Nullable String path) {
        if (path == null || path.trim().isEmpty()) return false;

        File f = new File(path);
        if (!f.exists()) {
            // Not a failure — already gone, which is the desired outcome.
            return false;
        }

        boolean deleted = f.delete();
        if (!deleted) {
            Log.w(TAG, "Failed to delete image file: " + path);
        } else {
            Log.d(TAG, "Deleted image file: " + path);
        }
        return deleted;
    }

    /**
     * Creates an empty File at the given location, suitable for writing into.
     *
     * Used by ImagePickerHelper to create a temporary destination file
     * before launching the camera intent (the camera writes directly to this path).
     * Parent directories are created if they don't exist.
     *
     * @param file The target File (should already have the correct path from a getXxxFile() call).
     * @return The same File if creation succeeded, or null if it failed.
     */
    @Nullable
    public File createEmptyFile(@NonNull File file) {
        try {
            File parent = file.getParentFile();
            if (parent != null && !parent.exists()) {
                if (!parent.mkdirs()) {
                    Log.e(TAG, "Failed to create parent directories for: " + file.getAbsolutePath());
                    return null;
                }
            }
            if (file.createNewFile()) {
                Log.d(TAG, "Created empty file: " + file.getAbsolutePath());
                return file;
            } else {
                // File already exists — this is acceptable (e.g. retry after a crash).
                Log.d(TAG, "File already exists (reusing): " + file.getAbsolutePath());
                return file;
            }
        } catch (IOException e) {
            Log.e(TAG, "Failed to create empty file: " + file.getAbsolutePath(), e);
            return null;
        }
    }

    // =========================================================================
    // GALLERY SCANNING (opt-in, for photos/ subdirectories only)
    // =========================================================================

    /**
     * Adds the given file to the device MediaStore so it appears in gallery apps.
     *
     * Only call this for files in photos/meals/ or photos/steps/ — never for
     * cache/thumbnails/ which is always private.
     *
     * The operation is asynchronous; the callback fires on a background thread
     * when scanning is complete. The callback may be null if the caller doesn't
     * need confirmation.
     *
     * @param file     The file to make visible in the gallery.
     * @param callback Optional callback; receives the file path and its new MediaStore URI.
     *                 Called on a background thread — post to main thread if updating UI.
     */
    public void scanFile(@NonNull File file, @Nullable MediaScannerConnection.OnScanCompletedListener callback) {
        MediaScannerConnection.scanFile(
                context,
                new String[]{ file.getAbsolutePath() },
                new String[]{ "image/jpeg" },
                callback
        );
        Log.d(TAG, "Requested gallery scan for: " + file.getAbsolutePath());
    }

    /**
     * Removes the given file from the device MediaStore gallery.
     *
     * This must be called BEFORE deleting the file from disk when the file was
     * previously gallery-scanned, so the MediaStore entry doesn't become a
     * dangling reference (which causes broken thumbnails in gallery apps).
     *
     * The operation queries MediaStore by DATA column (absolute path), which is
     * deprecated on API 29+ but remains the most reliable way to delete by path
     * without a URI. The DATA column is still readable for app-owned files.
     *
     * @param file The file to remove from the gallery.
     * @return true if a MediaStore entry was found and deleted, false otherwise.
     */
    public boolean unscanFile(@NonNull File file) {
        ContentResolver resolver = context.getContentResolver();
        Uri mediaUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;

        // Query by absolute path to find the MediaStore row ID.
        // DATA column is deprecated for new inserts but still valid for queries
        // on app-owned files stored in app-private external directories.
        String selection = MediaStore.Images.Media.DATA + " = ?";
        String[] selectionArgs = { file.getAbsolutePath() };

        try {
            int deleted = resolver.delete(mediaUri, selection, selectionArgs);
            if (deleted > 0) {
                Log.d(TAG, "Removed from gallery: " + file.getAbsolutePath());
                return true;
            } else {
                // Not in MediaStore — either never scanned, or already removed.
                Log.d(TAG, "File not found in gallery (no-op): " + file.getAbsolutePath());
                return false;
            }
        } catch (Exception e) {
            // Non-fatal — the file will still be deleted from disk.
            Log.w(TAG, "Failed to remove file from gallery: " + file.getAbsolutePath(), e);
            return false;
        }
    }

    // =========================================================================
    // INTERNAL HELPERS
    // =========================================================================

    /**
     * Ensures the given directory exists, creating it and any missing parents.
     *
     * @param dir The directory to create.
     * @return The directory if it exists (or was created), null if creation failed.
     */
    @Nullable
    private File ensureDir(@NonNull File dir) {
        if (dir.exists() && dir.isDirectory()) return dir;
        if (dir.mkdirs()) {
            Log.d(TAG, "Created directory: " + dir.getAbsolutePath());
            return dir;
        } else {
            Log.e(TAG, "Failed to create directory: " + dir.getAbsolutePath());
            return null;
        }
    }

    /**
     * Replaces characters that are illegal on FAT32/exFAT filesystems.
     *
     * Source-qualified IDs use ':' as a separator (e.g. "OFF:3017620422003").
     * Colons are invalid on FAT32/exFAT (common on external storage formatted
     * for cross-platform use). This method replaces ':' with '_', producing
     * a flat, safe filename like "OFF_3017620422003".
     *
     * @param id The source-qualified ID to sanitise.
     * @return A filesystem-safe version of the ID.
     */
    @NonNull
    private String sanitiseId(@NonNull String id) {
        // Replace colon (illegal on FAT32/exFAT) with underscore.
        // No other substitutions needed — source IDs are alphanumeric + colon only.
        return id.replace(':', '_');
    }
}