package li.masciul.sugardaddi.data.sources.themealdb.mappers;

import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import li.masciul.sugardaddi.core.enums.DataSourceType;
import li.masciul.sugardaddi.core.models.FoodPortion;
import li.masciul.sugardaddi.core.models.Recipe;
import li.masciul.sugardaddi.core.models.ServingSize;
import li.masciul.sugardaddi.core.models.SourceIdentifier;
import li.masciul.sugardaddi.data.network.ApiConfig;
import li.masciul.sugardaddi.data.sources.themealdb.TheMealDbConstants;
import li.masciul.sugardaddi.data.sources.themealdb.api.dto.MealDbIngredient;
import li.masciul.sugardaddi.data.sources.themealdb.api.dto.MealDbMeal;
import li.masciul.sugardaddi.data.sources.themealdb.api.dto.MealDbSearchResponse;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TheMealDbMapper — Maps TheMealDB DTOs to {@link Recipe} domain models.
 *
 * OUTPUT MODEL
 * ============
 * TheMealDB recipes map to {@link Recipe}, not {@link li.masciul.sugardaddi.core.models.FoodProduct}.
 * A recipe is a structured object with steps and ingredients — the Recipe domain
 * model already captures all of this correctly.
 *
 * LANGUAGE
 * ========
 * TheMealDB v1 is English-only. All content is stored under language "en"
 * ({@link Recipe#DEFAULT_LANGUAGE}). The language parameter is fixed — callers
 * do not need to pass it.
 *
 * NUTRITION
 * =========
 * TheMealDB provides NO nutrition data. The recipe's nutrition field is left null.
 * {@link Recipe#hasNutritionData()} will return false.
 * {@link Recipe#calculateNutrition()} will return zeros since no FoodProduct
 * references are resolved yet — ingredients are stored as unresolved stubs.
 * Nutrition can only be populated later by:
 *   1. The user manually entering it when editing the recipe (DataConfidence.USER)
 *   2. A future ingredient resolution step matching stub names against
 *      Ciqual/USDA/OFF products (DataConfidence.COMPUTED)
 *
 * INGREDIENT MAPPING
 * ==================
 * TheMealDB ingredients are unresolved plain-text strings ("soy sauce", "chicken").
 * They are stored as {@link FoodPortion} stubs:
 *   - itemType  = "FOOD_PRODUCT"   (the intended type when resolved)
 *   - itemId    = ingredient name  (used as display fallback by FoodPortion.getDisplayName())
 *   - foodProduct = null           (unresolved — no FoodProduct linked yet)
 *   - serving   = ServingSize(measure string)  (natural language, e.g. "3/4 cup")
 *   - preparationNote = null       (TheMealDB doesn't provide prep notes)
 *   - isEstimated = true           (quantity is unverified natural language)
 *
 * The serving is created with {@link ServingSize#ServingSize(String)} which stores
 * the raw measure string as description and attempts to parse quantity/unit.
 * For measures like "3/4 cup" or "1 (12 oz.)", parsing may succeed partially or
 * store the string as-is — both are acceptable since gram conversion is not
 * possible without a resolved FoodProduct density anyway.
 *
 * IDENTIFIERS
 * ===========
 * sourceIdentifier = SourceIdentifier("THEMEALDB", idMeal)
 * originalId       = idMeal (raw string from API, e.g. "52772")
 * The Recipe.id field is generated by Recipe's constructor and is a local UUID —
 * it is NOT the TheMealDB ID. Use originalId or sourceIdentifier for API round-trips.
 *
 * EPHEMERALITY
 * ============
 * TheMealDB recipes are never persisted to Room. They are created fresh on each
 * search or detail fetch. No RecipeEntity conversion is performed.
 */
public class TheMealDbMapper {

    private static final String TAG = "TheMealDbMapper";

    // TheMealDB is English-only — all content stored under this language key
    private static final String LANGUAGE = "en";

    // ========== PUBLIC API ==========

    /**
     * Map a search/lookup response to a list of Recipe domain models.
     *
     * Skips any meal that fails {@link MealDbMeal#isValid()} validation
     * or returns null from {@link #mapToDomainModel(MealDbMeal)}.
     *
     * @param response Deserialized API response envelope. May be null.
     * @return List of mapped recipes. Never null, may be empty.
     */
    @NonNull
    public List<Recipe> mapSearchResponse(@Nullable MealDbSearchResponse response) {
        List<Recipe> recipes = new ArrayList<>();

        if (response == null || !response.hasResults()) {
            return recipes;
        }

        for (MealDbMeal meal : response.getMeals()) {
            Recipe recipe = mapToDomainModel(meal);
            if (recipe != null) {
                recipes.add(recipe);
            }
        }

        Log.d(TAG, "Mapped " + recipes.size() + "/" + response.getCount()
                + " meals from TheMealDB response");

        return recipes;
    }

    /**
     * Map a single {@link MealDbMeal} DTO to a {@link Recipe} domain model.
     *
     * Returns null if the meal is invalid (missing ID or name) — callers
     * should skip null results silently.
     *
     * @param meal TheMealDB DTO. May be null.
     * @return Mapped Recipe, or null if meal is invalid.
     */
    @Nullable
    public Recipe mapToDomainModel(@Nullable MealDbMeal meal) {
        if (meal == null || !meal.isValid()) {
            Log.w(TAG, "Skipping invalid meal: " + meal);
            return null;
        }

        Recipe recipe = new Recipe();

        // ── Source identification ─────────────────────────────────────────────
        mapIdentification(recipe, meal);

        // ── Content fields ────────────────────────────────────────────────────
        mapContent(recipe, meal);

        // ── Ingredients → FoodPortion stubs ──────────────────────────────────
        mapIngredients(recipe, meal);

        // ── Tags ─────────────────────────────────────────────────────────────
        mapTags(recipe, meal);

        // ── Timestamps ───────────────────────────────────────────────────────
        recipe.setLastUpdated(System.currentTimeMillis());
        recipe.setCreatedAt(System.currentTimeMillis());

        // ── Completeness ─────────────────────────────────────────────────────
        // Calculates a quality score used by the search scorer.
        // TheMealDB recipes will score lower than user recipes (no times,
        // no difficulty, no structured steps) but will get credit for
        // having a name, description, instructions, image, and ingredients.
        recipe.calculateCompleteness();

        return recipe;
    }

    // ========== PRIVATE MAPPING METHODS ==========

    /**
     * Map source identification fields.
     *
     * Sets DataSource, SourceIdentifier, and originalId so the recipe
     * can be attributed and round-tripped back to the API by ID.
     */
    private void mapIdentification(@NonNull Recipe recipe, @NonNull MealDbMeal meal) {
        // Mark as externally sourced — NOT a user-created recipe
        recipe.setDataSource(DataSourceType.THEMEALDB);

        // SourceIdentifier("THEMEALDB", "52772") → searchableId = "THEMEALDB:52772"
        recipe.setSourceIdentifier(
                new SourceIdentifier(TheMealDbConstants.SOURCE_ID, meal.getIdMeal())
        );

        // Keep the raw TheMealDB ID for API lookups (e.g. detail screen refresh)
        recipe.setOriginalId(meal.getIdMeal());
    }

    /**
     * Map content fields: name, description, instructions, cuisine, image.
     *
     * All content is English-only — language is always set to "en".
     *
     * Description is composed from area + category since TheMealDB has no
     * dedicated description field. This gives the search result card a
     * meaningful subtitle (e.g. "Japanese · Chicken").
     */
    private void mapContent(@NonNull Recipe recipe, @NonNull MealDbMeal meal) {
        // Language is always English for TheMealDB v1
        recipe.setCurrentLanguage(LANGUAGE);

        // Name — guaranteed non-null by isValid() check above
        recipe.setName(meal.getStrMeal(), LANGUAGE);

        // Description — composed from area + category (no native description field)
        String description = buildDescription(meal.getStrArea(), meal.getStrCategory());
        if (description != null) {
            recipe.setDescription(description, LANGUAGE);
        }

        // Instructions — parse into structured steps using \r\n as the step delimiter.
        //
        // TheMealDB separates steps with \r\n (Windows line endings). Each non-empty
        // line after normalisation is one step. We populate stepStructure +
        // stepTranslations via Recipe.addStep() so that Recipe.getSteps(language)
        // returns properly numbered RecipeStep objects for the renderer.
        //
        // The raw blob is ALSO stored via setInstructions() as a plain-text fallback
        // for search indexing and any renderer that doesn't use structured steps.
        if (meal.getStrInstructions() != null
                && !meal.getStrInstructions().trim().isEmpty()) {

            String raw = meal.getStrInstructions().trim();

            // Store raw blob for search indexing and plain-text fallback
            recipe.setInstructions(raw, LANGUAGE);

            // Parse into structured steps
            String normalised = raw
                    .replace("\r\n", "\n")
                    .replace("\r", "\n")
                    .replaceAll("\n{3,}", "\n\n")
                    .trim();

            String[] lines = normalised.split("\n");
            for (String line : lines) {
                String step = line.trim();
                // Skip empty lines and bare numbers — TheMealDB sometimes
                // includes step numbers as standalone lines between instructions
                // (e.g. "2\r\nStep text\r\n3\r\nNext step text")
                if (step.isEmpty() || step.matches("^\\d+\\.?$")) {
                    continue;
                }

                // Strip leading step numbers — TheMealDB sometimes includes them inline
                // e.g. "1. Blend all..." → "Blend all..."
                //      "2) Taste and add..." → "Taste and add..."
                //      "Step 3: Fill..." → "Fill..."
                String cleaned = step
                        .replaceFirst("^[Ss]tep\\s+\\d+[.:\\-]?\\s*", "")  // "Step 3: " / "Step 3 "
                        .replaceFirst("^\\d+[.):\\-]\\s*", "");            // "1. " / "2) " / "3: "

                recipe.addStep(cleaned.trim(), null, null, LANGUAGE);
            }

            if (ApiConfig.DEBUG_LOGGING) {
                Log.d(TAG, "Parsed " + recipe.getSteps(LANGUAGE).size()
                        + " steps for: " + meal.getStrMeal());
            }
        }

        // Cuisine — the geographic area maps cleanly to cuisine
        // (e.g. "Japanese", "French", "Indian")
        if (meal.getStrArea() != null && !meal.getStrArea().trim().isEmpty()) {
            recipe.setCuisine(meal.getStrArea().trim());
        }

        // Image URL — CDN-hosted JPEG, load with Glide
        if (meal.getStrMealThumb() != null
                && !meal.getStrMealThumb().trim().isEmpty()) {
            recipe.setImageUrl(meal.getStrMealThumb().trim());
        }

        // Store the YouTube URL if present — available on the detail screen for
        // a direct video link. The "has_video" tag (set in mapTags) is kept as a
        // cheap boolean flag so the search card delegate can check video availability
        // without calling getVideoUrl() on every bind.
        if (meal.getStrYoutube() != null && !meal.getStrYoutube().trim().isEmpty()) {
            recipe.setVideoUrl(meal.getStrYoutube());
        }

        // Mark as a public recipe (not user-private)
        recipe.setPublic(true);
    }

    /**
     * Map TheMealDB's flat ingredient list to {@link FoodPortion} stubs.
     *
     * Each ingredient becomes an unresolved FoodPortion stub:
     * - itemType = "FOOD_PRODUCT" (target type when eventually resolved)
     * - itemId   = ingredient name (used as display fallback)
     * - foodProduct = null (no resolved product yet)
     * - serving  = ServingSize from measure string
     * - isEstimated = true (natural language measure, not precise)
     *
     * Ingredients with no name are skipped (handled by MealDbMeal.getIngredients()).
     * Ingredients with no measure get a ServingSize with null quantity — valid
     * but will display as "to taste" or the ingredient name only in the UI.
     */
    private void mapIngredients(@NonNull Recipe recipe, @NonNull MealDbMeal meal) {
        List<MealDbIngredient> ingredients = meal.getIngredients();

        if (ingredients.isEmpty()) {
            Log.w(TAG, "No ingredients found for meal: " + meal.getIdMeal()
                    + " (" + meal.getStrMeal() + ")");
            return;
        }

        List<FoodPortion> portions = new ArrayList<>(ingredients.size());

        for (int i = 0; i < ingredients.size(); i++) {
            MealDbIngredient ingredient = ingredients.get(i);

            // Build serving size from the natural language measure string.
            // ServingSize(String) stores it as description and attempts to parse.
            // For "3/4 cup": parseDescription() may extract quantity=0.75, unit=CUP.
            // For "1 (12 oz.)": will store as description only — that's acceptable.
            ServingSize serving;
            if (ingredient.hasMeasure()) {
                serving = new ServingSize(ingredient.getMeasure());
            } else {
                // No measure — create a ServingSize with unknown quantity.
                // getDisplayText() will return "Unknown serving" but the ingredient
                // name will still display via FoodPortion.getDisplayName() fallback.
                serving = new ServingSize();
            }

            // Build unresolved stub using the (itemType, itemId, serving) constructor.
            // itemId = ingredient name — this is the display fallback in FoodPortion.getDisplayName()
            // when foodProduct is null, which it will be until ingredient resolution.
            FoodPortion portion = new FoodPortion(
                    "FOOD_PRODUCT", // itemType — intended target type
                    ingredient.getName(),    // itemId — name used as display fallback
                    serving
            );

            // Mark ordering so the UI can display ingredients in API order
            portion.setOrderIndex(i);

            // All TheMealDB ingredient quantities are approximate natural language —
            // flag them so the UI can show an "estimated" indicator if desired.
            portion.setEstimated(true);

            // Parent context — this portion belongs to this recipe
            portion.setParentType("RECIPE");
            // Note: recipe.getId() is a local UUID set by Recipe's constructor.
            // At this point the recipe is not yet returned to the caller, but the
            // ID is already set — safe to reference here.
            portion.setParentId(recipe.getId());

            portions.add(portion);
        }

        recipe.setPortions(portions);

        Log.d(TAG, "Mapped " + portions.size() + " ingredient stubs for: "
                + meal.getStrMeal());
    }

    /**
     * Map tags from TheMealDB strTags and category.
     *
     * Sources:
     *   1. strTags parsed list (e.g. ["Meat", "Casserole"])
     *   2. strCategory (e.g. "Chicken") — added as a tag for search matching
     *   3. strArea (e.g. "Japanese") — added as a tag for cuisine filtering
     *
     * All tags are lowercased for consistent matching in RecipeScorer.
     */
    private void mapTags(@NonNull Recipe recipe, @NonNull MealDbMeal meal) {
        Set<String> tags = new HashSet<>();

        // Tags from strTags field
        for (String tag : meal.getParsedTags()) {
            tags.add(tag.toLowerCase());
        }

        // Category as tag
        if (meal.getStrCategory() != null && !meal.getStrCategory().trim().isEmpty()) {
            tags.add(meal.getStrCategory().trim().toLowerCase());
        }

        // Cuisine area as tag
        if (meal.getStrArea() != null && !meal.getStrArea().trim().isEmpty()) {
            tags.add(meal.getStrArea().trim().toLowerCase());
        }

        if (meal.getStrYoutube() != null && !meal.getStrYoutube().trim().isEmpty()) {
            tags.add("has_video");
        }

        if (!tags.isEmpty()) {
            recipe.setTags(tags);
        }
    }

    // ========== HELPERS ==========

    /**
     * Build the description string from area and category.
     *
     * Examples:
     *   area="Japanese", category="Chicken" → "Japanese · Chicken"
     *   area="Japanese", category=null      → "Japanese"
     *   area=null,       category="Chicken" → "Chicken"
     *   area=null,       category=null      → null
     *
     * @param area     strArea from TheMealDB (cuisine region). May be null.
     * @param category strCategory from TheMealDB. May be null.
     * @return Composed description, or null if both inputs are null/blank.
     */
    @Nullable
    private String buildDescription(@Nullable String area, @Nullable String category) {
        boolean hasArea     = area     != null && !area.trim().isEmpty();
        boolean hasCategory = category != null && !category.trim().isEmpty();

        if (hasArea && hasCategory) return area.trim() + " · " + category.trim();
        if (hasArea)                return area.trim();
        if (hasCategory)            return category.trim();
        return null;
    }
}